### ISSUE TITLE
Error while building an hadoop FAT jar

### ISSUE THREAD

**Issue by christian-lefty** [johnynek/bazel_jar_jar#17]
INFO: Analyzed target //databird/hadoop:shaded_cass_hello_deploy (842 packages loaded, 4694 targets configured).
INFO: Found 1 target...
ERROR: /home/christian/lefty/databird/hadoop/BUILD:38:19: jarjar //databird/hadoop:shaded_cass_hello_deploy failed: (Exit 1): jarjar_runner failed: error executing command bazel-out/host/bin/external/com_github_johnynek_bazel_jar_jar/jarjar_runner process databird/hadoop/shade_rules_hadoop bazel-out/k8-fastbuild/bin/databird/hadoop/cass_hello_deploy.jar ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 65536 out of bounds for length 132
	at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2679)
	at org.objectweb.asm.ClassReader.createLabel(ClassReader.java:2695)
	at org.objectweb.asm.ClassReader.readTypeAnnotations(ClassReader.java:2761)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1937)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.pantsbuild.jarjar.MethodSignatureProcessor.process(MethodSignatureProcessor.java:53)
	at org.pantsbuild.jarjar.util.JarProcessorChain.process(JarProcessorChain.java:38)
	at org.pantsbuild.jarjar.MainProcessor.process(MainProcessor.java:116)
	at org.pantsbuild.jarjar.util.StandaloneJarProcessor.run(StandaloneJarProcessor.java:46)
	at org.pantsbuild.jarjar.Main.process(Main.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.pantsbuild.jarjar.MainUtil.runMain(MainUtil.java:37)
	at org.pantsbuild.jarjar.Main.main(Main.java:50)
Target //databird/hadoop:shaded_cass_hello_deploy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.103s, Critical Path: 9.02s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully

Have you ever seen this?

**Comment by johnynek** [comment]
Sorry I didn't see this.

```
 Index 65536 out of bounds for length 132
```
that smells like an overflow for a large jar.

Maybe ASM9 fixes this: https://github.com/johnynek/bazel_jar_jar/pull/23
